### ISSUE TITLE
For events, adding "TBD" to date as start or end time

### ISSUE THREAD

**Issue by adamfranciscarr** [MarchonMilwaukee/MarchonMilwaukee.github.io#14]
I'm not sure if this functionality exists, but I know events will have a TBD for their start and end times to their date. I fiddled around a little, but didn't find a way to do it. I tried putting TBD after the date, but I just got the default time of 12:00am in the calendar.

Essentially, it would be handy if we could do a time like this: "Starts: Sep 7, 2017 at TBD"

Let me know if that's possible.

**Comment by mitchellhenke** [comment]
closed in #17
